# Generated by Django 4.2.7 on 2023-11-24 08:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re
import social_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
            ],
            options={
                'verbose_name': 'user post',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, validators=[social_app.models.validate_bad_words, django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[social_app.models.valide_email, django.core.validators.EmailValidator(message='enter a valid email')])),
                ('bio', models.TextField(blank=True, validators=[social_app.models.validate_bad_words])),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.PositiveIntegerField(null=True, validators=[social_app.models.validate_age])),
            ],
            options={
                'verbose_name': 'users from the app',
                'db_table': 'users table',
                'ordering': ['-joined_at', 'username'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique email/username'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_app.user'),
        ),
    ]
